server:
  port: 3600
management:
  security:
    enabled: false
spring:
  application:
    name: shop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wunai2010/shop
          search-paths: properties
